name = "Create: Gone Further"
author = "RedstoneWizard08"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a67216246a6f983e8a107e56e3a6eb905cd4bd120f30348fe5ada90db82b4d4d"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"
