name = "Create: Gone Further"
author = "RedstoneWizard08"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2821809d28c227280eb1158f88fe26b5640a2d38be31a711ca20b8c35edb4a09"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"
