name = "Create: Gone Further"
author = "RedstoneWizard08"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54de387282f980a9dfccf61b81e540b266f6fbed523c521158c11c24d12ce71c"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"
