name = "Alloy Forgery"
filename = "wraith-alloy-forgery-2.0.13+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3758/381/wraith-alloy-forgery-2.0.13+1.18.jar"
hash-format = "sha1"
hash = "1ced07990224e175037ce081f8b8e12b00793f66"