name = "Amecs (Fabric)"
filename = "amecs-1.3.8+mc.1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3819/652/amecs-1.3.8+mc.1.18.2.jar"
hash-format = "sha1"
hash = "801d5fef18825aa807cc15de3ec9dc34d15ce32f"