name = "Applied Energistics 2"
filename = "appliedenergistics2-11.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3836/462/appliedenergistics2-11.1.3.jar"
hash-format = "sha1"
hash = "7426271f4f82b5d3182b422bac0f7d0ae25e15bb"