name = "AutoSwitch [Fabric]"
filename = "autoswitch-4.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/961/autoswitch-4.0.3.jar"
hash-format = "sha1"
hash = "306452ef09e4bb1a749f2a0c249fb335ab9611e5"