name = "Bad Wither No Cookie - Reloaded [Fabric]"
filename = "badwithernocookiereloaded-3.10.18+(Fabric+1.18.2).jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3819/445/badwithernocookiereloaded-3.10.18+(Fabric+1.18.2).jar"
hash-format = "sha1"
hash = "285655f3434bc069039e5d08bd3a03cad5a248d8"