name = "Balm (Fabric Edition)"
filename = "balm-fabric-3.1.0+0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3830/796/balm-fabric-3.1.0+0.jar"
hash-format = "sha1"
hash = "0ad991574784541dffe9915e0ab731c66dab4f0a"