name = "BCLib"
filename = "bclib-1.4.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3814/359/bclib-1.4.7.jar"
hash-format = "sha1"
hash = "afc507e93908f0f27fcf68f333370264c8d49716"