name = "BetterF3"
filename = "BetterF3-1.2.5-Fabric-1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3798/366/BetterF3-1.2.5-Fabric-1.18.2.jar"
hash-format = "sha1"
hash = "457734b8099afbda9218c59aa6f197e2a2cc8d65"