name = "Better Biome Blend"
filename = "betterbiomeblend-1.18.2-1.3.5-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3804/87/betterbiomeblend-1.18.2-1.3.5-fabric.jar"
hash-format = "sha1"
hash = "65f2441618ab91a4b0c174b3bfbde89f894b3cba"