name = "Bits And Chisels"
filename = "bitsandchisels-2.6.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3841/573/bitsandchisels-2.6.13.jar"
hash-format = "sha1"
hash = "7106819d8aa8922022aac61696076f3360ab6a13"