name = "Boat Hud"
filename = "boathud-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3639/644/boathud-1.1.0.jar"
hash-format = "sha1"
hash = "1f4f09326dd650111cdab265ad742f96ea2e9c13"