name = "Chat Sounds"
filename = "chatsounds-1.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3747/31/chatsounds-1.1.3.jar"
hash-format = "sha1"
hash = "b0ae8f2abeed7fca508b80d7c722e893ada4a07d"