name = "Chromatic Currents"
filename = "chromatic-currents-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3752/200/chromatic-currents-1.0.1.jar"
hash-format = "sha1"
hash = "4b31d07c6f2953e620c4c1055a5e306cad623c29"