name = "Clumps"
filename = "Clumps-fabric-1.18.2-8.0.0+10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3833/878/Clumps-fabric-1.18.2-8.0.0+10.jar"
hash-format = "sha1"
hash = "d735c49013acdcbe9aecbaed43ddb6de5b838efa"