name = "Continuity"
filename = "continuity-2.0.0+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3822/250/continuity-2.0.0+1.18.2.jar"
hash-format = "sha1"
hash = "55c8fb90c3c3af60a3c3d2dc28aa0a6a1b866c5c"