name = "Cooldown Coordinator"
filename = "cooldown-coordinator-0.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3798/746/cooldown-coordinator-0.3.1.jar"
hash-format = "sha1"
hash = "a7a4c406ed720e5939106fc2576ca5d4d10584c5"