name = "Create Deco"
filename = "createdeco-1.2.7a-fabric-1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3810/882/createdeco-1.2.7a-fabric-1.18.2.jar"
hash-format = "sha1"
hash = "78e6da51f390c09257b3300ac5d8227eca086961"