name = "Create Fabric"
filename = "create-mc1.18.2_v0.4.1+631.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3835/278/create-mc1.18.2_v0.4.1+631.jar"
hash-format = "sha1"
hash = "38b3eb18cfc804b3ee15beed751762629a8b7576"