name = "Enchanted Vertical Slabs"
filename = "enchanted-vertical-slabs-1.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3747/24/enchanted-vertical-slabs-1.4.1.jar"
hash-format = "sha1"
hash = "5341295433555024a0721d0c325395467915de64"