name = "ExtraSounds"
filename = "extrasounds-2.3.1+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3829/238/extrasounds-2.3.1+1.18.2.jar"
hash-format = "sha1"
hash = "6e74bbec94b279c96e0808b9c454e2109618527d"