name = "[FABRIC] Disable Custom Worlds Advice"
filename = "DisableCustomWorldsAdvice-2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3677/546/DisableCustomWorldsAdvice-2.0.jar"
hash-format = "sha1"
hash = "3fd1adc79c42da6a7592c5d1c7fa413917782d86"