name = "Fabric Capes"
filename = "Capes-1.3.1+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3780/643/Capes-1.3.1+1.18.2.jar"
hash-format = "sha1"
hash = "407dc8d3a02785775deab32033d227a690481083"