name = "Fabric API"
filename = "fabric-api-0.56.1+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3840/106/fabric-api-0.56.1+1.18.2.jar"
hash-format = "sha1"
hash = "f24fae6a7065a769692f7a0eea5369be0eb0aacf"