name = "Falling Leaves (Fabric)"
filename = "fallingleaves-1.11.1+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3782/712/fallingleaves-1.11.1+1.18.2.jar"
hash-format = "sha1"
hash = "eaedf924b6774ef266ca0382d38c6325aa37f331"