name = "FastOpenLinksAndFolders"
filename = "fastopenlinksandfolders-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3806/979/fastopenlinksandfolders-1.1.1.jar"
hash-format = "sha1"
hash = "c24a170d663445455e3d8851c2dd5134499f336c"