name = "FTB Ultimine (Fabric)"
filename = "ftb-ultimine-fabric-1802.3.3-build.55.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3725/671/ftb-ultimine-fabric-1802.3.3-build.55.jar"
hash-format = "sha1"
hash = "4b8b8927ceca0da6c85abc7df256ed6203261eb9"