name = "FTB Library (Fabric)"
filename = "ftb-library-fabric-1802.3.6-build.123.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3822/757/ftb-library-fabric-1802.3.6-build.123.jar"
hash-format = "sha1"
hash = "2f88c98cbcc70470308d658e1dc822b5493b5b5e"