name = "Full Brightness Toggle (Fabric)"
filename = "fullbrightnesstoggle-fabric_1.18.x-1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/253/fullbrightnesstoggle-fabric_1.18.x-1.3.jar"
hash-format = "sha1"
hash = "ce9e9d86ce84723b89424a55f270095900fa7429"