name = "GeckoLib"
filename = "geckolib-fabric-1.18-3.0.49.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3844/297/geckolib-fabric-1.18-3.0.49.jar"
hash-format = "sha1"
hash = "6955828adbc39af37f1bbb1edd611acf21a2fa11"