name = "Hopper+ (Better Hoppers)"
filename = "hplus-1.18.2-3.3.0-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3787/619/hplus-1.18.2-3.3.0-fabric.jar"
hash-format = "sha1"
hash = "6a1215f30245321a45a18a35ae9bb4e2d12c232d"