name = "Indium"
filename = "indium-1.0.6+mc1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3840/291/indium-1.0.6+mc1.18.2.jar"
hash-format = "sha1"
hash = "057cdacd2d538c01594c5b4c140f452f5fac6ab2"