name = "JamLib"
filename = "jam-lib-0.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3802/327/jam-lib-0.0.5.jar"
hash-format = "sha1"
hash = "d2a3335f8e8efe10ccf0b7d34eb6c4ab3b36b506"