name = "Kibe Utilities"
filename = "kibe-1.9.8-BETA+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3842/7/kibe-1.9.8-BETA+1.18.jar"
hash-format = "sha1"
hash = "da42656eae425d95637cff1dc1c26c0e274bb01c"