name = "KubeJS"
filename = "kubejs-fabric-1802.5.4-build.502.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3844/401/kubejs-fabric-1802.5.4-build.502.jar"
hash-format = "sha1"
hash = "9f4252f8d238d7dc06358feb349ce17dc41753e6"