name = "lazy-language-loader (Fabric)"
filename = "lazy-language-loader-0.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/438/lazy-language-loader-0.3.0.jar"
hash-format = "sha1"
hash = "305a2f59667ae14efbfd11eca21aa30220ee764b"