name = "Lithium (Fabric)"
filename = "lithium-fabric-mc1.18.2-0.7.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3801/263/lithium-fabric-mc1.18.2-0.7.10.jar"
hash-format = "sha1"
hash = "d5c19c3d4edb4228652adcc8abb94f9bd80a634c"