name = "Macaw's Roofs - Oh The Biomes You'll Go"
filename = "macawsroofsbyg-fabric-1.18.2-1.0.jar"
side = "both"

[download]
url = "null"
hash-format = "sha1"
hash = "7d45e1081e70c953cd776b30d61301c234d70fc0"