name = "Macaw's Roofs"
filename = "mcw-roofs-2.1.2fabric-mc1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3760/194/mcw-roofs-2.1.2fabric-mc1.18.2.jar"
hash-format = "sha1"
hash = "f0139a96ea9b23b22f4c21ae5351d99b6ea13387"