name = "Macaw's Windows"
filename = "mcw-windows-2.0.3bfabric-mc1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3757/609/mcw-windows-2.0.3bfabric-mc1.18.2.jar"
hash-format = "sha1"
hash = "bdf5ab5175e83abcafea59f5e0a1a2c3ae4677b1"