name = "Macaw's Lights and Lamps"
filename = "mcw-lights-1.0.3c fabric-mc1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3750/59/mcw-lights-1.0.3c fabric-mc1.18.2.jar"
hash-format = "sha1"
hash = "6c8d9d8146dec6718ab87e026f4c953f20abe349"