name = "Macaw's Doors"
filename = "mcw-doors-1.0.6fabric-mc1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3740/800/mcw-doors-1.0.6fabric-mc1.18.2.jar"
hash-format = "sha1"
hash = "5a46ada98fc7e3240404a71328fcb9251e42b6ab"