name = "Macaw's Bridges - Oh The Biomes You'll Go"
filename = "macawsbridgesbyg-fabric-1.18.2-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3783/332/macawsbridgesbyg-fabric-1.18.2-1.2.jar"
hash-format = "sha1"
hash = "1a0869fd3af60c044b1ec40897afe211b60f8c90"