name = "Macaw's Paintings"
filename = "mcw-paintings-1.0.3fabric-mc1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3696/707/mcw-paintings-1.0.3fabric-mc1.18.2.jar"
hash-format = "sha1"
hash = "14159cc7454f5ea594117c0d82c4492301d66a16"