name = "MinecraftCapes Mod"
filename = "MinecraftCapes Fabric 1.18.2-12.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3673/296/MinecraftCapes Fabric 1.18.2-12.0.2.jar"
hash-format = "sha1"
hash = "fd7ac057c157b43e7295ef090cbbf9e200ce2a52"