name = "Missing Wilds"
filename = "MissingWilds-fabric-1.18.2-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3834/45/MissingWilds-fabric-1.18.2-1.1.0.jar"
hash-format = "sha1"
hash = "dc308fcfe936a766dee18b0ba5dcfbacd701b108"