name = "Modern Industrialization"
filename = "Modern-Industrialization-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3841/564/Modern-Industrialization-1.2.1.jar"
hash-format = "sha1"
hash = "a45cbd052c7ddf162dd3ae5550c0a731ebc058e4"