name = "oÏ‰o (owo-lib)"
filename = "owo-lib-0.7.2-no-cme+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3824/297/owo-lib-0.7.2-no-cme+1.18.jar"
hash-format = "sha1"
hash = "592c404a4a01608990abab9841279276267ae1fc"