name = "Oh The Biomes You'll Go Refabricated"
filename = "Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3825/948/Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4.1.jar"
hash-format = "sha1"
hash = "e1830850f1e3fc2b7a998c5c15f7009ba647152e"