name = "Patchouli (Fabric/Quilt)"
filename = "Patchouli-1.18.2-71-FABRIC.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3843/444/Patchouli-1.18.2-71-FABRIC.jar"
hash-format = "sha1"
hash = "8aa052ad5ede21de1e1ba99490a844b5af00ca63"