name = "Physics Mod"
filename = "physics-mod-2.7.3-mc-1.18.2-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3789/884/physics-mod-2.7.3-mc-1.18.2-fabric.jar"
hash-format = "sha1"
hash = "9760264ef571b519be1b1b6fd325500354c39703"