name = "Reborn Core"
filename = "RebornCore-5.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3798/506/RebornCore-5.2.0.jar"
hash-format = "sha1"
hash = "97c65e4c718f38cf2d43a5f99b53713e8d01ac56"