name = "Reese's Sodium Options"
filename = "reeses_sodium_options-1.4.3+mc1.18.2-build.42.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3820/947/reeses_sodium_options-1.4.3+mc1.18.2-build.42.jar"
hash-format = "sha1"
hash = "c39e06ad0bff8891046d80fb4c63fddfbe2d5bc4"