name = "Roughly Enough Items Fabric/Forge (REI)"
filename = "RoughlyEnoughItems-8.2.490.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3835/866/RoughlyEnoughItems-8.2.490.jar"
hash-format = "sha1"
hash = "e36c9514a6aff58ac80350b936b52d23ac2c5578"