name = "Simple Grinder"
filename = "simplegrinder-18_2.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3674/337/simplegrinder-18_2.0.2.jar"
hash-format = "sha1"
hash = "1ed313fb8ae78ae2a94b71e4b871b531fc001552"