name = "Simple Backpack [FABRIC]"
filename = "SimpleBackpack_Fabric-1.18.2-1.2.37.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3809/154/SimpleBackpack_Fabric-1.18.2-1.2.37.jar"
hash-format = "sha1"
hash = "645ff22ea3c080df8e3d12a2acf50bb2d560510f"