name = "Sodium Extra"
filename = "sodium-extra-0.4.5+mc1.18.2-build.42.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3821/6/sodium-extra-0.4.5+mc1.18.2-build.42.jar"
hash-format = "sha1"
hash = "79b569df32a953362b9006de60a84c857692e364"