name = "Sound Physics Remastered"
filename = "soundphysics-fabric-1.18.2-1.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3804/243/soundphysics-fabric-1.18.2-1.0.6.jar"
hash-format = "sha1"
hash = "414615a585c0d26bbf25f66a6608f06606fda4a5"