name = "Tech Reborn"
filename = "TechReborn-5.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3798/505/TechReborn-5.2.0.jar"
hash-format = "sha1"
hash = "224cef3683f7d589e931b2e1468da619fea1ca5d"