name = "The Forge - Modular Tools for Fabric"
filename = "the-forge-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3831/949/the-forge-1.1.0.jar"
hash-format = "sha1"
hash = "2260829707fd0f7d93edf66252ce651d6d8ddba3"