name = "Tool Stats"
filename = "ToolStats-Fabric-1.18.2-9.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3801/127/ToolStats-Fabric-1.18.2-9.0.3.jar"
hash-format = "sha1"
hash = "3dae7eb9f1adf2a8da12370a507dbac954adf414"