name = "Trinkets (Fabric)"
filename = "trinkets-3.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3786/685/trinkets-3.3.1.jar"
hash-format = "sha1"
hash = "1f6784a63d0c4cfe6caacf7b7a93ddd9f0b4e491"