name = "VanillaTweaks [Fabric & Forge]"
filename = "VanillaTweaks-fabric-1.18.2-1.5.58.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3759/363/VanillaTweaks-fabric-1.18.2-1.5.58.jar"
hash-format = "sha1"
hash = "868e9b9b1a11a0d3421370152f2d6f381413b131"