name = "You're in Grave Danger"
filename = "youre-in-grave-danger-1.3.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3807/315/youre-in-grave-danger-1.3.6.jar"
hash-format = "sha1"
hash = "8eaa2d3a90dc8a95c3d909586a4ffc750d6149a4"