name = "YUNG's Better Desert Temples (Fabric)"
filename = "YungsBetterDesertTemples-1.18.2-Fabric-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3818/724/YungsBetterDesertTemples-1.18.2-Fabric-1.1.0.jar"
hash-format = "sha1"
hash = "7ad56ccae0a9dd4c1fefdd82092dff4d77b78bb5"